const Truth = [
    "Tell us a story about the stupidest thing you’ve ever done while drunk.",
    "Did you ever sneak out of the house when you were younger?",
    "Did you drink before you reached the legal drinking age?",
    "Have you ever done drugs?",
    "What’s your guilty pleasure?",
    "What is your most embarrassing habit?",
    "If you could change one thing about yourself, what would it be?",
    "Have you ever accidentally walked into a wall?",
    "Do you talk to yourself sometimes?",
    "Is there anything in your web history you would be embarrassed about someone seeing?",
    "Do you have any weird habits when you sleep?",
    "Do you have a type?",
    "Who is your celebrity crush?",
    "What’s the biggest lie you’ve ever told?",
    "Out of the people you have dated, who were you most attracted to?",
    "Who gave you your biggest heartbreak?",
    "What’s your all-time favorite song to jam out to?",
    "How would you rate your appearance on a scale of 1-10?",
    "Do you think that you and your current partner will ever get married?",
    "What’s the most illegal thing you’ve ever done?",
    "Who is your favorite family member?",
    "Would you ever join the military?",
    "What is your biggest weakness?",
    "What is your biggest strength?",
    "What is your biggest pet peeve?",
    "If you were allowed to marry more than one person, would you?",
    "What’s your favorite TV show?",
    "What’s your favorite game to play?",
    "If you were to have a superpower, which would you choose?",
    "How much do you value money?",
    "If you could only be one, would you rather be successful or beautiful?",
    "How do you envision success?",
    "What’s your dream job?",
    "What’s your biggest fear?",
    "Do you have any phobias?",
    "What’s your drink of choice?",
    "Tell us about the drunkest you’ve ever been.",
    "Who do you like more, your mom or your dad?",
    "What’s your biggest regret?",
    "Have you ever regretted posting something on social media?",
    "What has been your proudest moment in life so far?",
    "What day was the happiest of your life so far?",
    "If you could go to dinner with any three people in history, dead or alive, who would you pick?",
    "If you could relive a year of your life, which would you pick?",
    "If you were going to die tomorrow, how would you spend today?",
    "If you won a million dollars, what’s the first thing you would spend it on?",
    "If you had the option of knowing when you would die and how, would you want to know? Why or why not?",
    "What children’s movies do you still enjoy?",
    "Have you ever been in a car accident?",
    "Which phone app do you spend the most time on?",
    "What’s the most painful injury you’ve ever gotten?",
    "What’s the meanest thing you’ve ever said to someone?",
    "How would you spend a day home alone?",
    "Do you save things you cherished as a child?",
    "If your house was on fire and you had the time to take one thing with you before you leave, what would you grab?",
    "Are you an early bird or a night owl?",
    "Have you ever had lice?",
    "What is your favorite flavor of ice cream?",
    "What’s your favorite type of food?",
    "What’s your death row meal?",
    "Who is your biggest role model?",
    "Who is your favorite person to spend time with?",
    "Have you ever had a crush on one of your teachers?",
    "Where are you, ticklish?",
    "What do you think is your best physical feature?",
    "Have you ever cheated on a test in school?",
    "Who is your guy celebrity crush?",
    "Who is your girl celebrity crush?",
    "Are you superstitious?",
    "Do you believe in karma?",
    "Do you believe in a higher power?",
    "Do you believe in love at first sight?",
    "Do you believe in fate?",
    "Where is the coolest place you’ve ever traveled to?",
    "What’s the strangest food combination you love?",
    "What movie never fails to make you cry?",
    "Have you ever been arrested or almost been arrested?",
    "If you were famous, what would you want it to be for?",
    "What’s your biggest insecurity?",
    "What do you feel passionate about?",
    "What cause do you feel extremely tied to?",
    "If you were to donate to a charity, which would you donate to?",
    "Have you ever pulled a prank on someone? Tell the group about it.",
    "Who is your least favorite family member?",
    "Have you ever lied on your resume?",
    "What is an instant deal-breaker for you in a new relationship?",
    "Have you ever been in a fight?",
    "When you’re home alone, do you walk around nude?",
    "Where is the worst place you’ve ever thrown up?",
    "What’s the worst thing you’ve ever eaten?",
    "Which is worse, physical pain or emotional pain?",
    "What destination is on your travel bucket list?",
    "Describe your dream date.",
    "What word do you hate hearing?",
    "If you could switch bodies with anyone who would you choose?",
    "What’s the worst rumor you’ve ever started or perpetuated about someone?",
    "Have you ever been fired?",
    "Who is the best kisser you’ve ever kissed?",
    "Have you ever met a famous person?",
    "What’s a skill you wish you were better at?",
    "Have you ever had your life flash before your eyes?",
    "Do you ever think there’s an excuse for cheating?",
    "Would you ever consider being in an open relationship?",
    "Have you ever compromised your morals for money?",
    "Have you ever cried by reading a book?",
    "What’s the best book you’ve ever read?",
    "What would be the worst way to die?",
    "What’s your favorite movie ever?",
    "Have you ever broken someone’s heart?",
    "How do you think other people see you?",
    "Who in the group gave you the worst first impression? Describe it.",
    "Have you ever compromised your morals for someone you love?",
    "What legacy do you want to leave behind?",
    "What’s your spirit animal?",
    "Tell us a story about the most scared you’ve ever been.",
    "If you had to get a tattoo, what would it be of?",
    "Do you believe in astrology?",
    "What’s the longest distance you’ve ever run?",
    "What’s the best piece of advice you’ve ever received?",
    "What’s the best lesson for a child to learn?",
    "What’s the worst hairstyle you’ve ever sported?",
    "Do you believe in aliens?",
    "Do you believe in ghosts?",
    "Have you ever said “I love you” and didn’t actually mean it?",
    "What’s the worst advice you’ve ever taken?",
    "Are you more of an introvert or an extrovert?",
    "How many children do you want to have one day?",
    "Are you competitive?",
    "Do you look at your poop before you flush the toilet?",
    "Have you ever sought revenge?",
    "What’s your least favorite memory?",
    "What’s your favorite holiday, and why?",
    "When’s the last time you internet stalked someone?",
    "What hobby would you love to take up?",
    "What’s your strangest obsession or pastime?",
    "What’s your favorite candy?",
    "Are you afraid of death?",
    "Who has the best butt in the room?",
    "What’s something you hold guilt over in your life?",
    "What’s your biggest turn on?",
    "What’s the biggest change you’ve ever gone through in life?",
    "What’s one of the hardest lessons you had to learn in life?",
    "What was your childhood nickname?",
    "What’s the worst present you’ve ever received?",
    "What’s the best present you’ve ever given?",
    "What’s the most attractive quality someone can have?",
    "What’s your biggest turn-off?",
    "Have you ever had an STI?",
    "Have you ever drank so much you don’t remember the night?",
    "Have you ever thrown up on someone else?",
    "If you had to, what would you get plastic surgery for?"
];

const Dare = [
    "Hum your favorite song and see if the group can guess what it is.",
    "Do your best touchdown dance.",
    "Pour a glass of ice water on your head.",
    "Time how long you can go without blinking.",
    "Time how long you can go without taking a breath.",
    "Let someone give you a wet willy.",
    "Let someone teabag you.",
    "Stick your hand in toilet water for 10 seconds.",
    "Do the salt and ice challenge.",
    "Lick your foot.",
    "Act like a gymnast and do your best cartwheel performance for the group.",
    "Show the group your most recently deleted photo.",
    "Cut off some of your hair.",
    "Let someone in the group tickle you for 30 seconds.",
    "Try to bite into and chew a piece of gum with the wrapper still on.",
    "Take a bite of an onion as if it’s an apple.",
    "Write a poem about someone in the room and see if the group can guess who it is.",
    "Put on makeup without looking in the mirror.",
    "Take a bite out of a stick of butter.",
    "Do the splits as best you can.",
    "Lick the elbow of the person sitting on your left.",
    "Post something on social media with a strange caption, and don’t delete it until your next turn.",
    "Do the worm.",
    "Try and moonwalk in front of the group.",
    "Lick your armpit.",
    "Let the player to your right, place your finger on a part of their body while your eyes are closed, then guess what you’re touching.",
    "Eat a slice of lemon as if it was an orange slice.",
    "Give the person to your right a foot massage.",
    "Do sit-ups until your next turn.",
    "Allow the players in the group to send a DM to one of your Instagram followers.",
    "Make out with your hand.",
    "Eat a dab of toothpaste.",
    "Sing the alphabet backward. For each letter you get wrong, you must do a punishment that is chosen by the group.",
    "Drink a mystery cocktail that the group creates.",
    "Perform your best yodel.",
    "Sensually lick the ear of the person sitting to your left.",
    "Take a small bite out of chapstick.",
    "Call a local place and ask them a stupid question about their menu.",
    "Take a body shot off of someone else in the room.",
    "Let someone in the group give you a makeover using only items from the fridge.",
    "Do the classic spaghetti scene from Lady & the Tramp with another player in the room.",
    "Draw a face on your stomach using your belly button as the mouth and talk as it until your next turn.",
    "Let another player in the group rock you like a baby.",
    "Chug a glass of milk.",
    "Without using your hands, remove another player‘s sock.",
    "Dance like a ballerina to music from The Nutcracker.",
    "If you’re a girl, let the group play a round of boob-sketball with your cleavage as the basket.",
    "Take a shower with your clothes on.",
    "Go next door and try to sell something to the neighbor.",
    "Give the player to your left a piggyback ride through the neighborhood.",
    "Wear your pants backward until your next turn.",
    "Eat a piece of dog or cat food.",
    "Do your best handstand for the group.",
    "Wall twerk for the group.",
    "Come up with a dance routine and perform it for the group. You have one minute to rehearse.",
    "Call your mom and convince her you’ve been arrested.",
    "Call your mom and convince her you’re engaged.",
    "Call your mom and tell her she’s going to be a grandma.",
    "Talk in old English until your next turn.",
    "Eat a piece of grass.",
    "Have another member in the group use a piece of floss, then wear it as a necklace until the round is over.",
    "Prank call the last person that called you.",
    "Put your finger into the nose of another group member.",
    "Put a pillow under your shirt and pretend to give birth.",
    "Lick an unused tampon or pad.",
    "Lick the floor.",
    "Smell another group member’s armpit.",
    "Pretend to seduce a stuffed animal.",
    "Let other players turn you into a mummy using toilet paper and stay like that until the round is over.",
    "Shave your arm.",
    "Cut the toenails of another player.",
    "Allow another player to punch you in the arm.",
    "Allow another player to give you a titty twister.",
    "Suck on your thumb until the round is over.",
    "Eat a piece of food like an animal.",
    "Place your hands into another player‘s pockets and keep them there until your next turn.",
    "Lick a dollar bill.",
    "Make your best impression of an animal of your choice.",
    "Do the burnie dance until the round is over.",
    "Brush another player‘s teeth using your finger.",
    "Leave the house and try to take a selfie with a stranger.",
    "Go outside and do your best to sell ice to the people walking by.",
    "Go outside, walk down the street and ask people what year it is as if you forgot.",
    "Paint your fingernails with a crayon.",
    "Connect with an old teacher on social media",
    "Eat a spoonful of salt.",
    "Read the last message you received aloud in a British accent.",
    "Perform like a mime for the next minute.",
    "Call a random number and express your deep love for the person on the other end. If they don’t answer, leave a voicemail.",
    "Call a random number and have a conversation with them about their day.",
    "Make your best impression of an auctioneer.",
    "Change your profile picture to your worst photo until the game ends.",
    "Take a shot of a condiment that the group chooses.",
    "Try to freestyle for the next minute.",
    "Romantically dance with a broom or a mop for the next minute.",
    "Do your best backbend.",
    "Talk with a crazy accent until your next turn.",
    "Do the chicken dance until the round is over.",
    "Perform a dance craze from your childhood for the group.",
    "Let another player spank you with a fly swatter.",
    "Smother your face in peanut butter until your next turn.",
    "Pour a glass of water without using your hands.",
    "Tape two cups to the front of your shirt until your next turn.",
    "Try to share a shirt with the person to your left.",
    "Dance the Macarena in the sexiest way possible.",
    "Go outside and try to sell something to the neighbor.",
    "Go outside, walk down the street and ask people what year it is as if you forgot.",
    "Draw a face on your stomach using your belly button as the mouth and talk as it until your next turn.",
    "Let another player in the group rock you like a baby.",
    "Chug a glass of milk.",
    "Without using your hands, remove another player‘s sock.",
    "Dance like a ballerina to music from The Nutcracker.",
    "If you’re a girl, let the group play a round of boob-sketball with your cleavage as the basket.",
    "Take a shower with your clothes on.",
    "Go next door and try to sell something to the neighbor.",
    "Give the player to your left a piggyback ride through the neighborhood.",
    "Wear your pants backward until your next turn.",
    "Eat a piece of dog or cat food.",
    "Do your best handstand for the group.",
    "Wall twerk for the group.",
    "Come up with a dance routine and perform it for the group. You have one minute to rehearse.",
    "Call your mom and convince her you’ve been arrested.",
    "Call your mom and convince her you’re engaged.",
    "Call your mom and tell her she’s going to be a grandma.",
    "Talk in old English until your next turn.",
    "Eat a piece of grass.",
    "Have another member in the group use a piece of floss, then wear it as a necklace until the round is over.",
    "Prank call the last person that called you.",
    "Put your finger into the nose of another group member.",
    "Put a pillow under your shirt and pretend to give birth.",
    "Lick an unused tampon or pad.",
    "Lick the floor.",
    "Smell another group member’s armpit.",
    "Pretend to seduce a stuffed animal.",
    "Let other players turn you into a mummy using toilet paper and stay like that until the round is over.",
    "Shave your arm.",
    "Cut the toenails of another player.",
    "Allow another player to punch you in the arm.",
    "Allow another player to give you a titty twister.",
    "Suck on your thumb until the round is over.",
    "Eat a piece of food like an animal.",
    "Place your hands into another player‘s pockets and keep them there until your next turn.",
    "Lick a dollar bill.",
    "Make your best impression of an animal of your choice.",
    "Do the burnie dance until the round is over.",
    "Brush another player‘s teeth using your finger.",
    "Leave the house and try to take a selfie with a stranger.",
    "Go outside and do your best to sell ice to the people walking by.",
    "Go outside, walk down the street and ask people what year it is as if you forgot.",
    "Paint your fingernails with a crayon.",
    "Connect with an old teacher on social media.",
    "Eat a spoonful of salt.",
    "Read the last message you received aloud in a British accent.",
    "Perform like a mime for the next minute.",
    "Call a random number and express your deep love for the person on the other end. If they don’t answer, leave a voicemail.",
    "Call a random number and have a conversation with them about their day.",
    "Make your best impression of an auctioneer.",
    "Change your profile picture to your worst photo until the game ends.",
    "Take a shot of a condiment that the group chooses.",
    "Try to touch your head with your feet."
];


export {
    Truth, Dare
}