const Truth = [
    "Have you ever eaten your own boogers?",
    "What’s the longest you’ve gone without showering?",
    "What’s the longest you’ve gone without brushing your teeth?",
    "Who would you hate to see naked?",
    "If you woke up as the opposite sex for one day, what would you do?",
    "Have you ever faked being sick to avoid a commitment like school or work?",
    "Have you ever walked in on someone else having sex?",
    "Has anyone ever walked in on you having sex?",
    "Describe the weirdest date you’ve been on.",
    "When’s the last time you ever wet the bed?",
    "What’s the funniest thing you’ve ever witnessed in person?",
    "Tell us about a hookup you would rather forget happened.",
    "Have you ever stolen something? What was your strategy?",
    "What was the weirdest thing you ever ate but pretended to enjoy?",
    "What’s the strangest dream you’ve ever had?",
    "Admit your worst fart story.",
    "Have you ever peed in a pool?",
    "Tell your worst hangover story.",
    "Would you rather date someone 20 years older or 20 years younger, and why?",
    "Did you have an imaginary friend when you were a child? What were they like?",
    "Have you ever practiced kissing in a mirror?",
    "What celebrity would you want to get trapped on an island with?",
    "What’s the largest amount of food you’ve eaten all at once?",
    "Out of everyone in the room, who would you pick to trade lives with for a day?",
    "Have you ever purposely made someone cry? Tell us your motives.",
    "What’s the awkwardest thing that’s happened to you when hooking up with someone?",
    "Did you sleep in your parent’s bed growing up? How old were you when you stopped?",
    "What’s the most embarrassing thing you’ve done to impress a crush?",
    "What do you think about while sitting on the toilet?",
    "Has anyone accidentally seen you naked? Tell us the details.",
    "Have you ever sent a text message to the wrong person? What did it say?",
    "What’s your most embarrassing habit?",
    "Have you ever had a major wardrobe malfunction in public?",
    "If you could read minds, how would you use the gift?",
    "Have you ever farted and blamed someone else?",
    "Have you ever accidentally walked into the wrong bathroom?",
    "Do you pick your nose when you’re alone?",
    "Do you pee in the shower?",
    "Have you ever peed your pants in public?",
    "Do you sleep with a stuffed animal at night?",
    "Who is the strangest person you’ve pleasured yourself to?",
    "Have you ever tasted earwax?",
    "How often do you change your sheets?",
    "How often do you wash your underwear?",
    "What’s the worst pick up line you’ve used while trying to attract someone’s attention.",
    "Do you smell your farts?",
    "What’s the strangest nickname you’ve ever been given?",
    "If you had to make out with a Disney character, who would you pick?",
    "What’s the cringiest trend you’ve participated in?",
    "Have you ever pooped yourself?",
    "What 'As Seen on TV' product do you secretly want to buy or have bought?"
];

const Dare = [
    "Put an ice cube down your pants until your next turn.",
    "Eat a spoonful of mayonnaise.",
    "Show us the last photo on your phone.",
    "Until your next turn, speak in your best British accent.",
    "Fill your mouth with water and recite the ABC’s.",
    "Pretend to make out with a pillow.",
    "Burp the alphabet as best you can.",
    "Perform your best belly dance.",
    "Do a naked lap around your backyard.",
    "Write your name on the floor with your tongue.",
    "Go on a social media app and the first account you see, click on them, and like as many photos of theirs as you can for 30 seconds.",
    "Try to eat a whole piece of paper.",
    "Let the group choose something you must attempt to brush your teeth with.",
    "Yell something crazy really loud outside of your house.",
    "Lick a car tire.",
    "Imitate someone in the room and don’t stop until the group guesses who it is.",
    "Lick someone’s foot.",
    "Imitate your best farting noises in front of the group.",
    "Let the group draw something on your face with a pen.",
    "Do a show and tell with the contents of your purse or wallet.",
    "Text the first 5 people in your contact list a random emoji.",
    "Lick a bar of soap.",
    "Smell everyone’s breath in the room and rank them best to worst.",
    "Jump into a dumpster or trash can.",
    "Lift the couch cushions and if there’s any food, place it in your mouth for 10 seconds.",
    "Let the rest of the group DM or message someone on your preferred social media app.",
    "Play “Chubby Bunny” in front of the group.",
    "Eat a raw piece of garlic.",
    "Eat a piece of raw onion.",
    "Eat a raw egg.",
    "Do your best twerking in front of the group for 30 seconds.",
    "Try your best to lick your elbow.",
    "Spin around 10 times and try to walk in a straight line.",
    "Shave off part of your eyebrow.",
    "Dye part of your hair a crazy color.",
    "Rub your hands under your armpits and then smell them.",
    "Let the group make a concoction out of things in the refrigerator and rub it on your face.",
    "Close your eyes and try to guess 5 foods that the group pulls from the kitchen.",
    "Dress up as the opposite sex and imitate them.",
    "Wear your underwear on your head for the rest of the game.",
    "Let your friends pose you a certain way and stay like that until your next turn.",
    "Trade socks with the player that’s to the right of you.",
    "Read through the first note you have on your phone.",
    "Have someone in the group put a leash on you and walk you around like you’re an animal.",
    "Wear the person across from you’s socks as if they’re gloves until your next turn.",
    "Perform a small concert of the song of your choice with props and everything.",
    "Let the person to your left gift you a wedgie.",
    "Pretend like you’re a dog until your next turn.",
    "Create a short song about the party host and perform it for the group.",
    "Ding dong ditch your neighbor’s house."
];


export {
    Truth, Dare
}