const Dare = [
    "Message something bold to someone hot you’ve been wanting to get to know.",
    "Kiss someone in the room that you’re attracted to.",
    "Fake your best orgasm in front of the group.",
    "Leave a sexy voicemail for your ex to listen to.",
    "Pick a position and imitate it with the person to your right.",
    "Sexily lick the food of your choice off the finger of the person to your left.",
    "Do a naked lap around the neighborhood.",
    "Find a position online that you’ve never tried and act it out on furniture that’s in the room.",
    "Prank call someone and pretend to be a sex ad.",
    "Trace the lips of someone here and whisper something sexy.",
    "Do a mini strip tease by taking off some of your clothing in front of the group.",
    "For the next round, you have to keep your hand on the inner thigh of the person to your left.",
    "Post something raunchy on your preferred social media app and you can’t remove it until the next round is over.",
    "Give someone else in the group a sexy massage while talking dirty.",
    "If there’s water nearby, it’s time to go skinny dipping!",
    "Time to play spin the bottle! Kiss whoever the bottle lands on.",
    "Close your eyes while a few members of the group stand across from you. Walk with your hands open until you touch one of them, then kiss them wherever your hand touched.",
    "Give the person to your left an eskimo kiss.",
    "You’ve been naughty, time to be put in time out on someone’s lap for the next round.",
    "Pick something small to sexily feed someone else in the group.",
    "Leave the room while everyone in the group pours a shot. When you come back, pick a shot to take. Whoever poured that shot, you have to kiss.",
    "Talk in a raunchy accent until your next turn.",
    "Scroll blindly through your contacts and whoever you land on, say one sexy thing about them.",
    "Give your best impression of a naughty cop who’s trying to arrest someone for being too sexy.",
    "Give the person to your right a butterfly kiss.",
    "Wink and do your best sexy face for the group.",
    "Pretend to have awful sex with the person to your right.",
    "Send bold, dirty message to someone you’ve hooked up with before.",
    "Call a phone sex line and pretend to have an odd fetish.",
    "Take a pen and paper and draw your penis or vagina.",
    "Facetime an old hookup. If they pick up, say something raunchy before hanging up.",
    "Fake a blowjob on a bottle.",
    "Describe your favorite position in detail but without saying what it is. See if the group can guess it!",
    "Perform a motorboat on someone. If you’re a girl, have someone do it to you.",
    "Send an up close and personal video of every part of you naked.",
    "Send a video of you singing in the shower.",
    "Post how you’re currently feeling on social media and don’t take it down until your next turn.",
    "Send me the naughtiest text that comes to mind.",
    "Go to the bathroom and make intense moans and grunts and send me a video for proof!",
    "Send me a dirty text in emojis that I have to figure out.",
    "Send photos of you acting out 5 dirty emojis.",
    "Write a sexy haiku and send it to me.",
    "Send me the ugliest selfie you have on your phone.",
    "Send whichever photo is 5 photos back in your camera roll.",
    "Send me the most recent text you sent to your best friend.",
    "Write me a quick naughty story and send it my way.",
    "Send a random emoji to the first person in your contacts with no explanation.",
    "Every time you receive a notification not from me, you have to remove an article of clothing.",
    "Send a video of you sexily licking something off your finger.",
    "Send a photo of you sexily sucking on something.",
    "Send a video of you trying to make out with your hand.",
    "Send a photo of what you think the least sexy part of your body is.",
    "Send a photo of what you think the sexiest part of your body is.",
    "Send me a photo of your sexiest pair of underwear.",
    "Go outside with no clothes on and send a photo for proof!",
    "Send a video of you trying to do a sexy dance move.",
    "Send a video of you giving a chair a lap dance.",
    "Draw a photo of me and send a picture of it to me.",
    "Imitate 12 swimsuit calendar poses and send them my way.",
    "Send me a sexy selfie with only your face.",
    "Let your partner pick what profile picture you get to have for the remainder of the evening.",
    "Demonstrate how you masturbate on an object in your room.",
    "Give a tutorial on your best sexual technique on something in your room.",
    "Slap yourself somewhere hot.",
    "Do a naked cartwheel and send a video.",
    "Order your partner something to eat and they have to try whatever it is.",
    "Change into the hottest outfit you have and pose in it like a model.",
    "Send a video of you pretending your butt is the one talking.",
    "Sing a song sexily into the camera.",
    "Cut off a little bit of your hair.",
    "Draw something on your face with marker.",
    "Try being sexy while holding your tongue and talking.",
    "Pick two things from your kitchen and use them to act out your favorite sex position.",
    "Send a photo of you naked with just shoes and a hat on.",
    "Call your partner and have them quiz you on basic math or trivia for a minute while you watch porn. Let’s see how good you do!",
    "Recreate a famous romance scene from a movie and send a video.",
    "Read a hot excerpt online or from a book aloud over a call or send a video.",
    "Have your partner pick random songs that you have to dirty dance to no matter what they are!",
    "Draw a photo of your partner and post it on social media with a sappy caption.",
    "Send a video of you attempting a popular dance move.",
    "Send a video of you trying to put on every piece of underwear you own.",
    "Send a video of you using your favorite sex toy.",
    "Send a video of you doing a strip tease.",
    "Order something sexy to wear when you see the other person.",
    "Send a video of you pleasuring yourself.",
    "Send a voice message of your best dirty talk.",
    "Send a voice message of your best sex moans.",
    "Send a video of you sexily licking your lips.",
    "Send a short video of you doing something you think will instantly get me aroused.",
    "Take off your bra with one hand and without taking off your shirt.",
    "Put an object in your pants and act like it’s your junk.",
    "Put someone’s underwear on your head.",
    "Wear your bra on your head like a hat for the rest of the game.",
    "Post a photo of a tampon on social media and don’t take it down until your next turn.",
    "Practice a sexy dance on a piece of furniture in the room.",
    "Touch tongues with someone else in the room.",
    "Shave part of your eyebrow.",
    "Dye part of your hair a daring color.",
    "Fake an orgasm for 10 seconds.",
    "Do a sexy crawl towards someone else in the room.",
    "Pretend to be any animal in a sexy way.",
    "Redress yourself in a guy’s clothing.",
    "Give a tutorial with an object in the room on how to pleasure a woman.",
    "Imitate how a guy flirts for 20 seconds and try to pick up someone in the room.",
    "Imitate a girl flirting for 20 seconds and try to pick up someone else in the room.",
    "Give a name to your package and explain why you named it how you did.",
    "Eat a snack in the sexiest way possible.",
    "Act out your favorite position with objects in the house.",
    "Demonstrate putting on a condom using a household object or food.",
    "Feed someone else in the room without using your hands.",
    "Redress yourself in a girl's clothing.",
    "Try to use makeup properly on your face and see how it turns out.",
    "Put something in your shirt and pretend to have boobs until the next round is over.",
    "Dye your hair a crazy color.",
    "Spank yourself while calling yourself a 'bad boy' for 20 seconds.",
    "Give your best impression of a sexy school girl."
];


const Truth = [
    "If you had to make out with anyone in this room, who would it be and why?",
    "Play 'fuck, marry, kill' with three people in the room.",
    "Where is the craziest place you’ve ever had sex?",
    "Tell the group about a sexual fantasy you have.",
    "Who was the worst you’ve ever had and the best you’ve ever had?",
    "Read us your best sexting line in a sexy accent.",
    "What’s the kinkiest thing you’ve ever done in bed?",
    "What’s the most adventurous thing you want to try in bed?",
    "Would you rather have sex with someone 20 years older or 20 years younger?",
    "What’s the biggest lie you’ve told someone to get them into bed with you?",
    "How old were you when you lost your virginity and how did it go?",
    "Who was your first kiss?",
    "What’s a popular fetish that you would never want to try?",
    "Do you remember the first time you experienced an orgasm? Tell us about it.",
    "What’s your favorite body part on your body?",
    "If you could have one sexual superpower, what would it be?",
    "Would you sleep with your boss if you could?",
    "What’s the least amount of time you’ve gone between having sex with two different people?",
    "What’s the most amount of people you’ve kissed in one night?",
    "Have you ever been tempted to cheat on your significant other?",
    "What’s your body count?",
    "What’s your favorite position?",
    "What’s the smallest amount of time you’ve known someone before sleeping with them?",
    "Have you ever been caught having sex?",
    "What position is popular that you think is overrated?",
    "Do you prefer sex when you’re in love or when it’s a hot hookup?",
    "Do you think virginity is special?",
    "Who is the oddest person you’ve ever had a sexual fantasy about?",
    "Do you think there’s an age where someone becomes 'too old' to be a virgin?",
    "Who in the room do you think has slept with the most people?",
    "Do you think there should be a limit on the amount of people you sleep with in your lifetime or do you think that doesn’t matter?",
    "Have you ever had sex and immediately gotten up and left?",
    "Have you ever called someone 'Daddy' or been called 'Daddy' while having sex?",
    "What do you wish you had learned about sex way earlier than you did?",
    "What fictional character have you or could you have sexual fantasies about?",
    "What are you wearing right now?",
    "Describe to me in detail your sexiest pair of underwear.",
    "What was your first impression of me?",
    "When did you have your first sexual feelings?",
    "When was your first sexual experience?",
    "What was your craziest sexual experience like?",
    "If I went through your bedside table, would I find anything fun or interesting?",
    "Where is your favorite place to be kissed on your body?",
    "If I was with you right now, what would you want to do to me?",
    "If I was with you right now, what would you want me to do to you?",
    "What’s the dirtiest thought you’ve ever had?",
    "What’s the dirtiest dream you’ve ever had?",
    "Where’s the raunchiest place you dream of having sex?",
    "Describe to me the best sex you’ve ever had.",
    "Have you ever had phone sex before?",
    "Who’s the one that got away?",
    "Are you turned on right now?",
    "Have you ever been tied up before?",
    "What is something that is completely off-limits from trying in bed?",
    "If you were to give a full-body massage, where would you start and end?",
    "What was your funniest sexual experience like?",
    "Have you ever had sex in public? Would you or would you again?",
    "What celebrity would you have sex with if you could?",
    "What’s on your mind right now?",
    "How can I get you horny?",
    "Have you ever done something that you feel guilty about?",
    "If I went through your room, would I find anything hidden or interesting?",
    "Describe your penis or vagina in detail, including what it likes, how it likes it, and how horny it is right now.",
    "What was your biggest sexual disappointment?",
    "Have you ever been sexually rejected?",
    "Describe the funniest mistake that’s happened to you while having sex.",
    "Do you have a name for your penis or vagina?",
    "What’s the hottest thing I can call your penis or vagina when we’re having sex?",
    "Do you own any sex toys?",
    "What kinds of sex toys would you want to try?",
    "Have you ever kissed someone of the same gender?",
    "Have you ever flashed someone?",
    "How long do you normally last in bed?",
    "Do you like sexting?",
    "Have you ever thought about me naked while talking to me?",
    "What automatically makes you orgasm during sex?",
    "Have you ever had or fantasized about an orgy?",
    "Have you ever had or fantasized about a threesome?",
    "Have you ever taken someone’s virginity?",
    "What excites you the most in bed?",
    "Have you ever masturbated in public?",
    "What’s your wildest sexual fantasy?",
    "What dirty secrets are you hiding?",
    "Have you ever tried anal sex?",
    "Do you like anal?",
    "Have you ever done something sexy with food during sex or foreplay?",
    "Describe what it was like the first time someone went down on you.",
    "Have you ever touched yourself while having sex?",
    "What’s the worst kiss you’ve ever had and why?",
    "What’s the best kiss you’ve ever had and why?",
    "What’s the most embarrassing wardrobe malfunction you’ve ever had?",
    "Have you had any awkward one-night stands?",
    "What’s the most romantic date you’ve ever been on?",
    "What’s the most thoughtful gift you’ve ever received in a relationship?",
    "What’s the most thoughtful gift you’ve ever given in a relationship?",
    "What’s the hottest body part on a guy?",
    "What’s the hottest body part on a girl?",
    "What’s the awkwardest crush you’ve ever had on someone?",
    "Describe the sexual encounter you regret the most.",
    "What was it like the first time you went down on someone?",
    "Spit or swallow?",
    "How often do you shave down there?",
    "Have you ever gotten a wax down there?",
    "If you were going to have a threesome, would you want the third party to be another girl or a guy?",
    "Have you ever been to a strip club?",
    "What’s something funny that turns you on?",
    "Do you get more horny when you’re on your period?",
    "Do you mind the taste when you go down on someone?",
    "Does body count matter to you?",
    "Would you ever go to a strip club?",
    "Have you ever tried to stick something that’s not a sex toy into your vagina?",
    "How old were you when you masturbated for the first time?",
    "Do you get turned on by nipple play?",
    "Have you ever had sex on your period?",
    "Do you enjoy having sex on your period?",
    "Which position is your least favorite and why?",
    "Which position is your favorite and why?",
    "Do you enjoy anal play?",
    "Have you ever gotten a UTI from sex?",
    "Do you own lingerie?",
    "What time of day do you prefer to have sex during?",
    "Where’s the most embarrassing place you’ve ever gotten a boner?",
    "What’s the hottest body part on a girl?",
    "What’s the hottest body part on a guy?",
    "Which male celebrity is the hottest in your opinion?",
    "Which celebrity would you do in an instant if you had the chance?",
    "When’s the last time you cried?",
    "What break-up broke your heart the most?",
    "What’s the craziest sex you’ve ever had?",
    "Have you ever gotten head while driving?",
    "Do you find lingerie hot?",
    "How large is your package?",
    "How old were you when you had your wet dream?",
    "Do you like to go all night or lay it all out in one fail swoop?",
    "Have you saved nudes from old hookups or exes?",
    "Do you like sending nudes?",
    "Have you ever gotten whiskey dick?",
    "Does body count matter to you?",
    "Does body count matter to you on your partner's end?",
    "Have you ever gotten an STI?",
    "What’s your favorite position and why?",
    "What time of day is your favorite to have sex during?",
    "Have you ever tried anal play? Thoughts?",
    "Do you own any sex toys or want to own some?",
    "Have you ever gotten blue balls?",
    "What’s the strangest thing you’ve ever gotten aroused from?",
    "Have you ever been to a strip club?",
    "Have you ever owned or used a blow-up doll?",
    "Have you ever worn a sexy piece of clothing?",
    "What’s the most romantic date you’ve ever been on?",
    "What’s the most thoughtful gift you’ve ever received in a relationship?",
    "What’s the most thoughtful gift you’ve ever given in a relationship?",
    "Have you ever had sex with a MILF? If not, do you want to?",
    "Do you mind the taste when you eat someone out?",
    "Have you ever tried to go down on yourself?",
    "Do you like it when girls play with your balls?",
    "Do you prefer to be shaved or keep it hairy down there?",
    "If you were going to have a threesome, would you want the third party to be another girl or a guy?"
];

export {
    Dare,
    Truth
}